---
apiVersion: app.lykon.io/v1
kind: XLykonLambdaDockerImage
metadata:
  name: test-lambda
  namespace: platform
spec:
  parameters:
    env: staging
    service_name: gdpr-deleter-srv
    stream: staging-gdpr
    commit_hash: some-hash
    secrets:
      notesPlain: null
      LOG_LEVEL: info
      OFFSET_DAYS: "14"
      METRICS_SERVICE_NAME: gdpr_deleter_srv
      SKIP_EXPORTER: "true"
      EXPORTER_BASE_URL: http://gdpr-exporter-srv
      DELETER_BASE_URL: http://gdpr-deleter-srv.platform.svc.cluster.local
      DELETER_BATCH_SIZE: "10"
      GRPC_TARGET: dns:///gdpr-deleter-srv.platform.svc.cluster.local:8081
      DATABASE_DSN: postgres://postgres:!aN*9aiGrT9dEP64QHwnMk-7@gdpr-deleter-db:5432/gdpr_deleter?sslmode=disable
