on:
  workflow_call:
    inputs:
      role_name:
        required: true
        type: string
      role_session_name:
        required: true
        type: string
      aws_region:
        required: false
        type: string
        default: eu-central-1
      ecr_repo_name:
        required: true
        type: string
      docker_file_path:
        required: true
        type: string
      docker_image_prefix:
        required: false
        type: string
        default: ""
      build_args:
        required: false
        type: string
        default: ""
      provenance:
        required: false
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read
  pull-requests: write
  statuses: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      id: aws
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ inputs.role_name }}
        role-session-name: ${{ inputs.role_session_name }}
        aws-region: ${{ inputs.aws_region }}

    - name: Docker meta Service
      id: metadata-srv
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/lykon/${{ inputs.ecr_repo_name }}
        flavor: |
          latest=false
        tags: |
          type=sha,event=branch,format=long,prefix=${{ inputs.docker_image_prefix }}

    - name: Login to ECR
      id: ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registries: ${{ secrets.AWS_ACCOUNT_ID }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v4.1.1
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-single-buildx-srv
        restore-keys: |
          ${{ runner.os }}-single-buildx

    - name: Build and push application
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ${{ inputs.docker_file_path }}
        push: true
        tags: ${{ steps.metadata-srv.outputs.tags }}
        build-args: |
          GITHUB_TOKEN=${{ secrets.GB_TOKEN_PRIVATE }}
          ${{ inputs.build_args }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        provenance: ${{ inputs.provenance }}
      env:
        VERSION: ${{ github.sha }}

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
