name: Renovate

on:
  workflow_call:
    inputs:
      renovate_file_path:
        required: true
        type: string

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ubuntu-latest Renovate
        uses: renovatebot/github-action@v32.241.11
        with:
          configurationFile: ${{ inputs.renovate_file_path }}
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
