name: Renovate

on:
  schedule:
    - cron: '0 10 * * 1'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.66.1
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GB_TOKEN_PRIVATE }}
        env:
          LOG_LEVEL: 'debug'
