on:
  workflow_call:
    inputs:
      main_branch:
        required: false
        type: string
        default: main

jobs:
  linter:
    name: Linter
    # Set the agent to run on
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          GOPRIVATE: github.com/vimeda/*
          DEFAULT_BRANCH: ${{ inputs.main_branch }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_DOCKERFILE: true
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_OPENAPI: true
          VALIDATE_YAML: true
          GITHUB_TOKEN: ${{ secrets.GB_TOKEN_PRIVATE }}

  golang:
    name: Lint Golang files
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.19.0"

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.GB_TOKEN_PRIVATE }}
        run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/vimeda".insteadOf "https://github.com/vimeda"

      - name: Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true
          args: -c ./.github/linters/.golangci.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GB_TOKEN_PRIVATE }}
