on:
  workflow_call:
    inputs:
      entity_name:
        required: true
        type: string
      entity_kind:
        required: true
        type: string
      entity_namespace:
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  pull-requests: write
  statuses: write

jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
      - uses: actions/setup-python@v2

      - name: Configure AWS Credentials
        id: aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-backstage-role
          role-session-name: ga-backstage
          aws-region: eu-central-1

      - name: Install techdocs-cli
        run: sudo npm install -g @techdocs/cli

      - name: Install mkdocs and mkdocs plugins
        run: python -m pip install mkdocs-techdocs-core==1.*

      - name: Generate docs site
        run: techdocs-cli generate --no-docker --verbose

      - name: Publish docs site
        run: techdocs-cli publish --publisher-type awsS3 --storage-name ${{ secrets.TECHDOCS_S3_BUCKET_NAME }} --entity ${{ inputs.entity_namepsace }}/${{ inputs.entity_kind }}/${{ inputs.entity_name }}
