on:
  workflow_call:
    inputs:
      php_version:
        required: false
        type: string
        default: 8.1
      php_extensions:
        required: false
        type: string
        default: grpc
      make_test_goal:
        required: false
        default: test
        type: string

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php_version }}
        tools: composer:v2
        extensions: ${{ inputs.php_extensions }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache composer dependencies
      uses: actions/cache@v4.1.1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install dependencies
      run: |
        export COMPOSER_AUTH="{\"github-oauth\":{\"github.com\":\"${GITHUB_TOKEN}\"}}"
        composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      env:
        GITHUB_TOKEN: ${{ secrets.GB_TOKEN_PRIVATE }}

    - name: Test
      run: make ${{ inputs.make_test_goal }}
